force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <description>An &quot;Invoice&quot; object serves as a formal document in real estate transactions, outlining the financial obligations and details of services rendered or property-related expenses. It typically includes information such as the names of involved parties, a description of services or products, the associated property or transaction, the invoice amount, payment terms, and a due date. In the real estate industry, invoices are used to request and track payments for services provided, such as agent commissions, property maintenance, or other transaction-related expenses. The Invoice object is essential for financial record-keeping, ensuring transparency and facilitating efficient payment processing in real estate transactions.</description>
    <label>Invoice for Buyers</label>
    <nameField>
        <displayFormat>INV-{0000000}</displayFormat>
        <label>Invoice Record ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Buyer__c.field-meta.xml
<CustomField>
    <fullName>Buyer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Buyer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Listing__c.field-meta.xml
<CustomField>
    <fullName>Listing__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Listing</label>
    <referenceTo>Listings__c</referenceTo>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Payment_Schedule__c.field-meta.xml
<CustomField>
    <fullName>Payment_Schedule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Schedule</label>
    <referenceTo>Payment_Schedule__c</referenceTo>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Buyer__c.field-meta.xml
<CustomField>
    <fullName>Buyer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Buyer</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.AccountId</field>
            <operation>equals</operation>
            <valueField>Contact.AccountId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Deals</relationshipLabel>
    <relationshipName>Deals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Listing__c.field-meta.xml
<CustomField>
    <fullName>Listing__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Listing</label>
    <referenceTo>Listings__c</referenceTo>
    <relationshipLabel>Deals</relationshipLabel>
    <relationshipName>Deals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Schedule__c/Payment_Schedule__c.object-meta.xml
<CustomObject>
    <description>A &quot;Payment Schedule&quot; object outlines the timing and details of financial transactions within a real estate deal, specifying due dates, amounts, and parties involved. It ensures organized and timely payment execution, promoting financial transparency in real estate transactions.</description>
    <label>Payment Schedule</label>
    <nameField>
        <displayFormat>PS-{0000000}</displayFormat>
        <label>Payment Schedule RecordID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Schedule__c/fields/Amortization__c.field-meta.xml
<CustomField>
    <fullName>Amortization__c</fullName>
    <label>Amortization</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payment_Schedule__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deal</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Payment Schedules</relationshipLabel>
    <relationshipName>Payment_Schedules</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Schedule__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Invoice</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Payment Schedules</relationshipLabel>
    <relationshipName>Payment_Schedules</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/BatchInvoiceGenarator.cls
global class BatchInvoiceGenarator implements Database.Batchable<sObject>,schedulable{
    global Database.QueryLocator start(Database.BatchableContext BC) {
        // collect the batches of records or objects to be passed to execute
        
        String query = 'SELECT Id, Deal__c,  Deal__r.Buyer__c, Deal__r.Listing__c, Amortization__c FROM Payment_Schedule__c WHERE Invoice__c = NULL';
        System.debug('*** query *** ' + query);

        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, List<Payment_Schedule__c> paymentScheduleList) {
        try {
            System.debug('*** paymentScheduleList *** ' + paymentScheduleList);

            // Generate the invoice per payment schedule
            List<Invoice__c> batchInvoices = new List<Invoice__c>();         
            List<Payment_Schedule__c> batchSchedule = new List<Payment_Schedule__c>();               

            // process each batch of records default size is 200
            for(Payment_Schedule__c ps :  paymentScheduleList) {        
                Invoice__c invoice = new Invoice__c();
                invoice.Opportunity__c = ps.Deal__c;
                invoice.Buyer__c = ps.Deal__r.Buyer__c;
                invoice.Listing__c = ps.Deal__r.Listing__c;
                invoice.Amount__c = ps.Amortization__c;
                invoice.Payment_Schedule__c = ps.Id;
                invoice.Invoice_Date__c = System.today();
                batchInvoices.add(invoice);
            }            

            // insert invoices
            if(!batchInvoices.isEmpty()){
                insert batchInvoices;
            }  
            
            // loop into invoices to update the payment schedules
            System.debug('*** batchInvoices *** ' + batchInvoices);
            if (!batchInvoices.isEmpty()){
                for (Invoice__c i: batchInvoices){
                    Payment_Schedule__c ps = new Payment_Schedule__c();
                    ps.id = i.Payment_Schedule__c;
                    ps.Invoice__c = i.Id;
                    batchSchedule.add(ps);
                }

                if (!batchSchedule.isEmpty()){
                    update batchSchedule;
                }
            }
        } catch(Exception e) {
            // put email notification here in case of error
            System.debug(e.getMessage());
        } 
    }   
     
    global void finish(Database.BatchableContext BC) {
        list<string> eml = new list<string>();
        // execute any post-processing operations like sending email
        list<user> UserList = [Select id,email from user where Profile.Name = 'System Administrator'];
        for(user us: UserList){
            if(us.email != null){
                // eml.add(us.email);
            }
        }
        String email = 'rd@valuehubit.com';
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();

        mail.setToAddresses(new String[] {email});
       
        mail.setSenderDisplayName('Batch Processing');
        mail.setSubject('Batch Process has Completed');
        mail.setPlainTextBody('Batch Processing for Create Invoce has been Completed');
        
        //mail.setToAddresses(new List<string>(eml));
        

        Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });

    }
    
     public  void execute(Schedulablecontext sc){
        BatchInvoiceGenarator  cr=new BatchInvoiceGenarator();
        Database.executeBatch(cr, 40);
    }
    


}