force-app/main/default/objects/Listings__c/Listings__c.object-meta.xml
<CustomObject>
    <description>A &quot;Listing&quot; is a data object representing a property available for sale or rent in the real estate industry. It typically includes property details (type, location, size), pricing information, contact details, and a unique identifier for tracking. Listings are fundamental for property search and real estate transactions.</description>
    <label>Listing</label>
    <nameField>
        <label>Listings Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Listings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Listings__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Listings__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <label>Property</label>
    <referenceTo>Property__c</referenceTo>
    <relationshipLabel>Listings</relationshipLabel>
    <relationshipName>Listings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <description>A &quot;Property&quot; object represents a physical real estate asset, such as a house, apartment, commercial space, or land. It serves as a fundamental data structure in real estate databases and platforms. A typical Property object includes essential attributes, such as property type, location, size, and associated features, providing comprehensive information for buyers, renters, and real estate professionals. This object plays a central role in real estate listings and transactions, facilitating property search, evaluation, and decision-making.</description>
    <label>Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Property_Image__c/Property_Image__c.object-meta.xml
<CustomObject>
    <label>Property Image</label>
    <nameField>
        <label>Property Image Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Property Images</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Property_Image__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Property</label>
    <referenceTo>Listings__c</referenceTo>
    <relationshipLabel>Property Images</relationshipLabel>
    <relationshipName>Property_Images</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Property_Image__c/fields/Property_Image_URL__c.field-meta.xml
<CustomField>
    <fullName>Property_Image_URL__c</fullName>
    <label>Property Image URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/classes/appiontmentDetailslwc_Apxcls.cls
public class appiontmentDetailslwc_Apxcls {
	@AuraEnabled(cacheable=true)
    public static Listings__c getRelatedDocs(Id recordId){
        Listings__c lst = [Select Id,Description__c,Property__r.Name,( Select Id,Property_Image_URL__c,Name from Property_Images__r ) from Listings__c Where Id =: recordId];
        return lst;
    }
    
    @AuraEnabled(cacheable=true)
    public static List<Object> getlookupdetails(String objectname , String searchkey,Boolean filtering, String filteringfield,String parentid){
        String queryString = 'SELECT Id, Name from '+objectname;
        if( !String.isEmpty( searchkey ) ){
             String queryName = searchkey + '%%';
            queryString += ' Where Name like :queryName';
            if( filtering == true ){
                if( !String.isEmpty( parentid ) && parentid !='blank'){
                    queryString += ' AND '+filteringfield+' =:parentid';
                }
                
            }
            System.debug(queryString);
            return Database.query(queryString);
        }else{
            return new List<object>();
        }
        
        
    }
    
    
}