force-app/main/default/objects/City__c/City__c.object-meta.xml
<CustomObject>
    <label>City</label>
    <nameField>
        <label>City Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>City</label>
    <referenceTo>City__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>State</label>
    <referenceTo>State__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract__c/Contract__c.object-meta.xml
<CustomObject>
    <description>A &quot;Contract&quot; object is a legally binding document that formalizes the terms and conditions of a real estate transaction. It encompasses crucial information such as property details, parties involved (buyer and seller), purchase price, financing terms, contingencies, and key dates. In real estate, contracts are fundamental for outlining the responsibilities and obligations of both parties and are a necessary step in property transactions. The Contract object ensures clarity and legal compliance, facilitating the buying and selling of real estate properties.</description>
    <label>Contract</label>
    <nameField>
        <displayFormat>CI-{0000000}</displayFormat>
        <label>Contract ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contract__c/fields/Buyer__c.field-meta.xml
<CustomField>
    <fullName>Buyer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Buyer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract__c/fields/Deals__c.field-meta.xml
<CustomField>
    <fullName>Deals__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deals</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract__c/fields/Listing__c.field-meta.xml
<CustomField>
    <fullName>Listing__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Listing</label>
    <referenceTo>Listings__c</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <label>Country</label>
    <nameField>
        <label>Counrty Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Listings__c/Listings__c.object-meta.xml
<CustomObject>
    <description>A &quot;Listing&quot; is a data object representing a property available for sale or rent in the real estate industry. It typically includes property details (type, location, size), pricing information, contact details, and a unique identifier for tracking. Listings are fundamental for property search and real estate transactions.</description>
    <label>Listing</label>
    <nameField>
        <label>Listings Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Listings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Listings__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>City</label>
    <referenceTo>City__c</referenceTo>
    <relationshipLabel>Listings</relationshipLabel>
    <relationshipName>Listings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Listings__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Listings</relationshipLabel>
    <relationshipName>Listings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Listings__c/fields/No_of_Bathrooms__c.field-meta.xml
<CustomField>
    <fullName>No_of_Bathrooms__c</fullName>
    <label>No.of Bathrooms</label>
    <precision>12</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Listings__c/fields/No_of_Bedrooms__c.field-meta.xml
<CustomField>
    <fullName>No_of_Bedrooms__c</fullName>
    <label>No.of Bedrooms</label>
    <precision>12</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Listings__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <label>Property</label>
    <referenceTo>Property__c</referenceTo>
    <relationshipLabel>Listings</relationshipLabel>
    <relationshipName>Listings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Listings__c/fields/Seller__c.field-meta.xml
<CustomField>
    <fullName>Seller__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Property (Listing Owner)</inlineHelpText>
    <label>Seller</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Listings</relationshipLabel>
    <relationshipName>Listings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Listings__c/fields/Square_footage__c.field-meta.xml
<CustomField>
    <fullName>Square_footage__c</fullName>
    <label>Square footage</label>
    <length>254</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Listings__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>State</label>
    <referenceTo>State__c</referenceTo>
    <relationshipLabel>Listings</relationshipLabel>
    <relationshipName>Listings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <description>A &quot;Property&quot; object represents a physical real estate asset, such as a house, apartment, commercial space, or land. It serves as a fundamental data structure in real estate databases and platforms. A typical Property object includes essential attributes, such as property type, location, size, and associated features, providing comprehensive information for buyers, renters, and real estate professionals. This object plays a central role in real estate listings and transactions, facilitating property search, evaluation, and decision-making.</description>
    <label>Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/State__c/State__c.object-meta.xml
<CustomObject>
    <label>State</label>
    <nameField>
        <label>State Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>States</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ContractController.cls
public with sharing class ContractController {

    public String companyLogo {get;set;}
    public ContractWrapperClass cwc {get;set;}

    public ContractController() {
        try{
            String contract_id = ApexPages.currentPage().getParameters().get('id');

            cwc = new ContractWrapperClass();

            List<Contract__c> contract = [SELECT Id, Listing__r.Name, Deals__c, Buyer__r.Name, Buyer__r.MailingAddress, Listing__r.Property__r.Name,
                                          Buyer__r.City__r.Name, Buyer__r.Country__r.Name, Buyer__r.State__r.Name, Buyer__r.Street__c,
                                          Listing__r.Property__r.Street__c, Listing__r.Property__r.City__r.Name, 
                                          Listing__r.Property__r.State__r.Name, Listing__r.Property__r.Country__r.Name,
                                          Listing__r.Property__r.Seller__r.Name, Listing__r.No_of_Bedrooms__c, Listing__r.No_of_Bathrooms__c,
                                          Listing__r.Square_footage__c
                                          FROM Contract__c WHERE Id =: contract_id];
            
            if (!contract.isEmpty()){
                cwc.company_logo = 'https://vusr-dev-ed--c.develop.vf.force.com/resource/1700436470000/CompanyLogo';             
                cwc.buyer_address = contract.get(0).Buyer__r.Street__c + ' ' + contract.get(0).Buyer__r.City__r.Name + ' ' + contract.get(0).Buyer__r.State__r.Name + ' ' + contract.get(0).Buyer__r.Country__r.Name;
                cwc.buyer_name = contract.get(0).Buyer__r.Name;
                cwc.buyer_state = contract.get(0).Buyer__r.State__r.Name;
                cwc.property_name = contract.get(0).Listing__r.Property__r.Name;
                cwc.property_address = contract.get(0).Listing__r.Property__r.Street__c + ' ' + contract.get(0).Listing__r.Property__r.City__r.Name + ' ' + contract.get(0).Listing__r.Property__r.State__r.Name + ' ' + contract.get(0).Listing__r.Property__r.Country__r.Name;
                cwc.property_state = contract.get(0).Listing__r.Property__r.State__r.Name;
                cwc.property_city = contract.get(0).Listing__r.Property__r.City__r.Name;

                cwc.unit_name = contract.get(0).Listing__r.Name;
                cwc.unit_description = contract.get(0).Listing__r.Name + ' | ' + contract.get(0).Listing__r.No_of_Bedrooms__c + ' bd | ' + contract.get(0).Listing__r.No_of_Bathrooms__c + ' ba | ' + contract.get(0).Listing__r.Square_footage__c + ' Sqft';

                cwc.seller_name = contract.get(0).Listing__r.Property__r.Seller__r.Name;

            }

            System.debug('*** wrapper *** ' + cwc);

            this.companyLogo = 'https://vusr-dev-ed--c.develop.vf.force.com/resource/1700436470000/CompanyLogo';
        
        }catch(Exception e){
            System.debug('*** Exception ContractController *** ' + e.getMessage());
        }
    }

    private class ContractWrapperClass{
        public String company_logo {get;set;}
        public String property_name {get;set;}
        public String property_address {get;set;}
        public String property_state {get;set;}
        public String property_city {get;set;}
    
        public String unit_name {get;set;}
        public String unit_description {get;set;}

        public String seller_name {get;set;}

        public String buyer_name {get;set;}
        public String buyer_address {get;set;}
        public String buyer_street {get;set;}
        public String buyer_city {get;set;}
        public String buyer_state {get;set;}
        public String buyer_country {get;set;}
    }

}