force-app/main/default/objects/City__c/City__c.object-meta.xml
<CustomObject>
    <label>City</label>
    <nameField>
        <label>City Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/City__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>State</label>
    <referenceTo>State__c</referenceTo>
    <relationshipLabel>Cities</relationshipLabel>
    <relationshipName>Cities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>City</label>
    <referenceTo>City__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>State</label>
    <referenceTo>State__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <label>Country</label>
    <nameField>
        <label>Counrty Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <description>An &quot;Invoice&quot; object serves as a formal document in real estate transactions, outlining the financial obligations and details of services rendered or property-related expenses. It typically includes information such as the names of involved parties, a description of services or products, the associated property or transaction, the invoice amount, payment terms, and a due date. In the real estate industry, invoices are used to request and track payments for services provided, such as agent commissions, property maintenance, or other transaction-related expenses. The Invoice object is essential for financial record-keeping, ensuring transparency and facilitating efficient payment processing in real estate transactions.</description>
    <label>Invoice for Buyers</label>
    <nameField>
        <displayFormat>INV-{0000000}</displayFormat>
        <label>Invoice Record ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Broker__c.field-meta.xml
<CustomField>
    <fullName>Broker__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Broker</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Invoices1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Buyer__c.field-meta.xml
<CustomField>
    <fullName>Buyer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Buyer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Full_Payment__c.field-meta.xml
<CustomField>
    <fullName>Full_Payment__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Full Payment</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Listing__c.field-meta.xml
<CustomField>
    <fullName>Listing__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Listing</label>
    <referenceTo>Listings__c</referenceTo>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Listings__c/Listings__c.object-meta.xml
<CustomObject>
    <description>A &quot;Listing&quot; is a data object representing a property available for sale or rent in the real estate industry. It typically includes property details (type, location, size), pricing information, contact details, and a unique identifier for tracking. Listings are fundamental for property search and real estate transactions.</description>
    <label>Listing</label>
    <nameField>
        <label>Listings Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Listings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Listings__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>City</label>
    <referenceTo>City__c</referenceTo>
    <relationshipLabel>Listings</relationshipLabel>
    <relationshipName>Listings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Listings__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Listings</relationshipLabel>
    <relationshipName>Listings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Listings__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Listings__c/fields/Listing_Price__c.field-meta.xml
<CustomField>
    <fullName>Listing_Price__c</fullName>
    <label>Listing Price</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Listings__c/fields/Lot__c.field-meta.xml
<CustomField>
    <fullName>Lot__c</fullName>
    <label>Lot</label>
    <length>254</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Listings__c/fields/No_of_Bathrooms__c.field-meta.xml
<CustomField>
    <fullName>No_of_Bathrooms__c</fullName>
    <label>No.of Bathrooms</label>
    <precision>12</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Listings__c/fields/No_of_Bedrooms__c.field-meta.xml
<CustomField>
    <fullName>No_of_Bedrooms__c</fullName>
    <label>No.of Bedrooms</label>
    <precision>12</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Listings__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <label>Property</label>
    <referenceTo>Property__c</referenceTo>
    <relationshipLabel>Listings</relationshipLabel>
    <relationshipName>Listings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Listings__c/fields/Square_footage__c.field-meta.xml
<CustomField>
    <fullName>Square_footage__c</fullName>
    <label>Square footage</label>
    <length>254</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Listings__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>State</label>
    <referenceTo>State__c</referenceTo>
    <relationshipLabel>Listings</relationshipLabel>
    <relationshipName>Listings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Listings__c/fields/Street_Name__c.field-meta.xml
<CustomField>
    <fullName>Street_Name__c</fullName>
    <label>Street Name</label>
    <length>254</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Listings__c/fields/Type_of_unit__c.field-meta.xml
<CustomField>
    <fullName>Type_of_unit__c</fullName>
    <label>Type of unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Single</fullName>
            </value>
            <value>
                <fullName>Family</fullName>
            </value>
            <value>
                <fullName>Residence</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Listings__c/fields/Year_built__c.field-meta.xml
<CustomField>
    <fullName>Year_built__c</fullName>
    <label>Year built</label>
    <length>254</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <description>A &quot;Property&quot; object represents a physical real estate asset, such as a house, apartment, commercial space, or land. It serves as a fundamental data structure in real estate databases and platforms. A typical Property object includes essential attributes, such as property type, location, size, and associated features, providing comprehensive information for buyers, renters, and real estate professionals. This object plays a central role in real estate listings and transactions, facilitating property search, evaluation, and decision-making.</description>
    <label>Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Property__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>City</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>City__c.State__c</field>
            <operation>equals</operation>
            <valueField>$Source.State__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>City__c</referenceTo>
    <relationshipLabel>Properties</relationshipLabel>
    <relationshipName>Properties</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Properties</relationshipLabel>
    <relationshipName>Properties</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>State</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>State__c.Country__c</field>
            <operation>equals</operation>
            <valueField>$Source.Country__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>State__c</referenceTo>
    <relationshipLabel>Properties</relationshipLabel>
    <relationshipName>Properties</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Street__c.field-meta.xml
<CustomField>
    <fullName>Street__c</fullName>
    <label>Street</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/State__c/State__c.object-meta.xml
<CustomObject>
    <label>State</label>
    <nameField>
        <label>State Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>States</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/State__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>States</relationshipLabel>
    <relationshipName>States</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/generateInvoiceController.cls
public with sharing class generateInvoiceController {
    
    public String companyLogo {get;set;}
    public InvoiceClass invoice {get;set;}

    public generateInvoiceController() {
        try{
            String invoice_id = ApexPages.currentPage().getParameters().get('id');

            this.invoice = new InvoiceClass();
            this.invoice.company_logo = 'https://vusr-dev-ed--c.develop.vf.force.com/resource/1700436470000/CompanyLogo';
            
            List<Invoice__c> invoice = [SELECT Id, Name, Amount__c, Broker__c, Buyer__r.Name, Buyer__r.MailingAddress, Full_Payment__c, Listing__r.Name, Invoice_Date__c, Opportunity__c FROM Invoice__c WHERE Id =: invoice_id];
            List<Listings__c> unit = [SELECT Id, Name, Property__r.Name, Property__r.Country__r.Name, Property__r.City__r.Name, Property__r.State__r.Name, Property__r.Street__c, 
                                        Country__r.Name, City__r.Name, State__r.Name, Description__c, Lot__c, Listing_Price__c,
                                        Type_of_unit__c, No_of_Bathrooms__c, No_of_Bedrooms__c, Street_Name__c, Year_built__c, Square_footage__c 
                                        FROM Listings__c WHERE Id =: invoice.get(0).Listing__c];

            
            this.invoice.invoice_number = invoice.get(0).Name;
            this.invoice.buyer_name = invoice.get(0).Buyer__r.Name;
            this.invoice.invoice_date = invoice.get(0).Invoice_Date__c;
            this.invoice.acquired_unit = invoice.get(0).Listing__r.Name;
            this.invoice.street = unit.get(0).Street_Name__c;
            
            this.invoice.unit_price = unit.get(0).Listing_Price__c;
            this.invoice.amount = invoice.get(0).Amount__c;

            this.invoice.unit_name = unit.get(0).Name;
            this.invoice.type_of_unit = unit.get(0).Type_of_unit__c;
            this.invoice.square_foot = unit.get(0).Square_footage__c;
            this.invoice.no_of_bedrooms = unit.get(0).No_of_Bedrooms__c;
            this.invoice.no_of_bathrooms = unit.get(0).No_of_Bathrooms__c;
            this.invoice.year_built = unit.get(0).Year_built__c;

            this.invoice.description = unit.get(0).Name + ' ' + unit.get(0).Type_of_unit__c + ' ' + unit.get(0).Square_footage__c + ' ' + String.valueOf(unit.get(0).No_of_Bedrooms__c);
                
            

            // this.invoice.description = 

            this.invoice.property_name = unit.get(0).Property__r.Name;
            this.invoice.property_country = unit.get(0).Property__r.Country__r.Name;
            this.invoice.property_city = unit.get(0).Property__r.City__r.Name;
            this.invoice.property_state = unit.get(0).Property__r.State__r.Name;
            this.invoice.property_street = unit.get(0).Property__r.Street__c;

            System.Address c = invoice.get(0).Buyer__r.MailingAddress;

            this.invoice.street = c.street;
            this.invoice.city = c.city;
            this.invoice.state = c.state;
            this.invoice.postal_code = c.postalcode;
            this.invoice.country = c.country;
            
            System.debug('*** country *** ' + c.country);

            System.debug('*** invoice *** ' + this.invoice);

        }catch(Exception e){
            System.debug('*** PRINT INVOICE: *** ' + e.getMessage());
        }
    }

    public class InvoiceClass{
        public String buyer_name {get;set;}
        public String broker_name {get;set;}
        public Decimal amount {get;set;}
        public Decimal unit_price {get;set;}
        public Date invoice_date {get;set;}
        public String invoice_number {get;set;} 
        public String fully_paid {get;set;} 
        public String acquired_unit {get;set;} 
        public String company_logo {get;set;}
        public String country {get;set;}
        public String state {get;set;}
        public String city {get;set;}
        public String street {get;set;}
        public String postal_code {get;set;}
        public String property_name {get;set;}
        public String property_city {get;set;}
        public String property_state {get;set;}
        public String property_country {get;set;}
        public String property_street {get;set;}

        public String type_of_unit {get;set;}
        public String square_foot {get;set;}
        public Decimal no_of_bedrooms {get;set;}
        public Decimal no_of_bathrooms {get;set;}
        public String year_built {get;set;}
        public String unit_name {get;set;}
        
        public String description {get;set;}

        public InvoiceClass(){
            this.buyer_name = '';
            this.broker_name = '';
            this.amount = 0.00;
            this.invoice_number = '';
        }
    }


}