force-app/main/default/objects/City__c/City__c.object-meta.xml
<CustomObject>
    <label>City</label>
    <nameField>
        <label>City Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/City__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>State</label>
    <referenceTo>State__c</referenceTo>
    <relationshipLabel>Cities</relationshipLabel>
    <relationshipName>Cities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Listings__c/Listings__c.object-meta.xml
<CustomObject>
    <description>A &quot;Listing&quot; is a data object representing a property available for sale or rent in the real estate industry. It typically includes property details (type, location, size), pricing information, contact details, and a unique identifier for tracking. Listings are fundamental for property search and real estate transactions.</description>
    <label>Listing</label>
    <nameField>
        <label>Listings Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Listings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Listings__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>City</label>
    <referenceTo>City__c</referenceTo>
    <relationshipLabel>Listings</relationshipLabel>
    <relationshipName>Listings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Listings__c/fields/Latitude__c.field-meta.xml
<CustomField>
    <fullName>Latitude__c</fullName>
    <label>Latitude</label>
    <scale>2</scale>
    <type>Location</type>
</CustomField>

force-app/main/default/objects/Listings__c/fields/Longitude__c.field-meta.xml
<CustomField>
    <fullName>Longitude__c</fullName>
    <label>Longitude</label>
    <scale>2</scale>
    <type>Location</type>
</CustomField>

force-app/main/default/objects/Listings__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <label>Property</label>
    <referenceTo>Property__c</referenceTo>
    <relationshipLabel>Listings</relationshipLabel>
    <relationshipName>Listings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Listings__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>State</label>
    <referenceTo>State__c</referenceTo>
    <relationshipLabel>Listings</relationshipLabel>
    <relationshipName>Listings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Listings__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Off-Market</fullName>
                <default>true</default>
                <label>Off-Market</label>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Under Contract</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Sold</fullName>
            </value>
            <value>
                <fullName>Rented</fullName>
            </value>
            <value>
                <fullName>Hold</fullName>
            </value>
            <value>
                <fullName>Reserved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Listings__c/fields/Street_Name__c.field-meta.xml
<CustomField>
    <fullName>Street_Name__c</fullName>
    <label>Street Name</label>
    <length>254</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <description>A &quot;Property&quot; object represents a physical real estate asset, such as a house, apartment, commercial space, or land. It serves as a fundamental data structure in real estate databases and platforms. A typical Property object includes essential attributes, such as property type, location, size, and associated features, providing comprehensive information for buyers, renters, and real estate professionals. This object plays a central role in real estate listings and transactions, facilitating property search, evaluation, and decision-making.</description>
    <label>Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Property__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>City</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>City__c.State__c</field>
            <operation>equals</operation>
            <valueField>$Source.State__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>City__c</referenceTo>
    <relationshipLabel>Properties</relationshipLabel>
    <relationshipName>Properties</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Property_Type__c.field-meta.xml
<CustomField>
    <fullName>Property_Type__c</fullName>
    <description>This picklist  for the different type properties</description>
    <inlineHelpText>Please Select the the Property Type</inlineHelpText>
    <label>Property Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Retail</fullName>
            </value>
            <value>
                <fullName>Multi Family</fullName>
            </value>
            <value>
                <fullName>Self Storage</fullName>
            </value>
            <value>
                <fullName>Single family residence</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Property__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>State</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>State__c.Country__c</field>
            <operation>equals</operation>
            <valueField>$Source.Country__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>State__c</referenceTo>
    <relationshipLabel>Properties</relationshipLabel>
    <relationshipName>Properties</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Sold</fullName>
            </value>
            <value>
                <fullName>Rented</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Property_Image__c/Property_Image__c.object-meta.xml
<CustomObject>
    <label>Property Image</label>
    <nameField>
        <label>Property Image Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Property Images</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Property_Image__c/fields/Image__c.field-meta.xml
<CustomField>
    <fullName>Image__c</fullName>
    <formula>IF(ISBLANK(Property_Image_URL__c), &apos;&apos;, IMAGE(Property_Image_URL__c, &quot;Image&quot;))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Image</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Property_Image__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Property</label>
    <referenceTo>Listings__c</referenceTo>
    <relationshipLabel>Property Images</relationshipLabel>
    <relationshipName>Property_Images</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Property_Image__c/fields/Property_Image_URL__c.field-meta.xml
<CustomField>
    <fullName>Property_Image_URL__c</fullName>
    <label>Property Image URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/State__c/State__c.object-meta.xml
<CustomObject>
    <label>State</label>
    <nameField>
        <label>State Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>States</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/RealStateDynamicController.cls
// public with sharing class RealStateDynamicController {
//     @AuraEnabled(cacheable=true)
//     public static List<ListingWithImages> getListingsWithImages() {
//         List<ListingWithImages> listingDataList = new List<ListingWithImages>();

//         List<Listings__c> listings = [SELECT Id, Name, Latitude__c, Longitude__c, City__r.Name, State__r.Name, Property__r.Name, Property__r.Status__c, Property__r.Property_Type__c,
//             (SELECT Id, Image__c,Property_Image_URL__c FROM Property_Images__r) FROM Listings__c limit 100] ;

//         for (Listings__c listing : listings) {
//             ListingWithImages listingData = new ListingWithImages();
//             listingData.Id = listing.Id;
//             listingData.Name = listing.Name;
          
//             listingData.City = listing.City__r.Name;
//             listingData.State = listing.State__r.Name;
//             listingData.PropertyName = listing.Property__r.Name;
//             listingData.Status = listing.Property__r.Status__c;
//             listingData.PropertyType = listing.Property__r.Property_Type__c;

//             for (Property_Image__c image : listing.Property_Images__r) {
//                 listingData.ImageURLs.add(image.Image__c);
//             }

//             listingDataList.add(listingData);
//         }

//         return listingDataList;
//     }

//     public class ListingWithImages {
//         @AuraEnabled
//         public String Id { get; set; }
//         @AuraEnabled
//         public String Name { get; set; }

//         @AuraEnabled
//         public String City { get; set; }
//         @AuraEnabled
//         public String State { get; set; }
//         @AuraEnabled
//         public String PropertyName { get; set; }
//         @AuraEnabled
//         public String Status { get; set; }
//         @AuraEnabled
//         public String PropertyType { get; set; }
//         @AuraEnabled
//         public List<String> ImageURLs { get; set; }

//         public ListingWithImages() {
//             ImageURLs = new List<String>();
//         }
//     }
// }


// public with sharing class RealStateDynamicController {
//     @AuraEnabled(cacheable=true)
//     public static List<Listings__c> getListingsWithImages() {
//         List<Listings__c> listingDataList = new List<Listings__c>();

//         List<Listings__c> listings = [
//             SELECT Id, Name, Latitude__c, Longitude__c, City__r.Name, State__r.Name, Property__r.Name, Property__r.Status__c, Property__r.Property_Type__c,
//             (SELECT Id, Image__c, Property_Image_URL__c FROM Property_Images__r)
//             FROM Listings__c
//         ];

//         // Populate listingDataList with the queried data
//         listingDataList.addAll(listings);
      
//         return listingDataList;
//     }
// }


// public with sharing class RealStateDynamicController {
//     @AuraEnabled(cacheable=true)
//     public static List<Listings__c> getListingsByCity(String city) {
//         List<Listings__c> listingDataList = new List<Listings__c>();

//         List<Listings__c> listings = [
//             SELECT Id, Name, Latitude__c, Longitude__c, City__r.Name, State__r.Name, Property__r.Name, Property__r.Status__c, Property__r.Property_Type__c,
//             (SELECT Id, Image__c, Property_Image_URL__c FROM Property_Images__r)
//             FROM Listings__c
//             WHERE City__r.Name = :city
//         ];

//         // Populate listingDataList with the filtered data
//         listingDataList.addAll(listings);
      
//         return listingDataList;
//     }
//}


/*
public with sharing class RealStateDynamicController {
    @AuraEnabled(cacheable=true)
    public static List<Listings__c> getListingsByCity(String city) {
        List<Listings__c> listingDataList = new List<Listings__c>();

        List<Listings__c> listings = [
            SELECT Id, Name, City__r.Name, Latitude__c, Longitude__c
            FROM Listings__c
            WHERE City__r.Name = :city
        ];

        // Populate listingDataList with the filtered data
        listingDataList.addAll(listings);

        return listingDataList;
    }
}
*/


public with sharing class RealStateDynamicController {
    @AuraEnabled(cacheable=true)
    public static List<Listings__c> getListingsByCity() {
        

        List<Listings__c> listings = [
            SELECT Id, Name,Street_Name__c, Latitude__c, Longitude__c, City__r.Name, State__r.Name, Property__r.Name, Property__r.Status__c, Property__r.Property_Type__c,
            (SELECT Id, Image__c, Property_Image_URL__c FROM Property_Images__r)
            FROM Listings__c];

      
        return listings;
    }
}