force-app/main/default/objects/City__c/City__c.object-meta.xml
<CustomObject>
    <label>City</label>
    <nameField>
        <label>City Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/City__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>State</label>
    <referenceTo>State__c</referenceTo>
    <relationshipLabel>Cities</relationshipLabel>
    <relationshipName>Cities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>City</label>
    <referenceTo>City__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>State</label>
    <referenceTo>State__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Buyer.recordType-meta.xml
<RecordType>
    <fullName>Buyer</fullName>
    <active>true</active>
    <label>Buyer</label>
</RecordType>

force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <label>Country</label>
    <nameField>
        <label>Counrty Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <description>A &quot;Property&quot; object represents a physical real estate asset, such as a house, apartment, commercial space, or land. It serves as a fundamental data structure in real estate databases and platforms. A typical Property object includes essential attributes, such as property type, location, size, and associated features, providing comprehensive information for buyers, renters, and real estate professionals. This object plays a central role in real estate listings and transactions, facilitating property search, evaluation, and decision-making.</description>
    <label>Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Property__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>City</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>City__c.State__c</field>
            <operation>equals</operation>
            <valueField>$Source.State__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>City__c</referenceTo>
    <relationshipLabel>Properties</relationshipLabel>
    <relationshipName>Properties</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Properties</relationshipLabel>
    <relationshipName>Properties</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>State</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>State__c.Country__c</field>
            <operation>equals</operation>
            <valueField>$Source.Country__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>State__c</referenceTo>
    <relationshipLabel>Properties</relationshipLabel>
    <relationshipName>Properties</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/publicevent__e/publicevent__e.object-meta.xml
<CustomObject>
    <label>publicevent</label>
    <pluralLabel>publicevents</pluralLabel>
</CustomObject>

force-app/main/default/objects/Reservation__c/Reservation__c.object-meta.xml
<CustomObject>
    <description>A &quot;Reservation&quot; object represents a formal booking or temporary hold on a real estate property. It includes essential details such as the reserved property, reservation dates, reserving party&apos;s information, and terms of the reservation. Reservations in real estate enable clients to secure specific dates for property viewings or inspections. This object streamlines the scheduling process, prevents overlapping appointments, and enhances the overall client experience in the real estate industry.</description>
    <label>Reservation</label>
    <nameField>
        <displayFormat>RES-{0000000}</displayFormat>
        <label>Record ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reservations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Reservation__c/fields/Buyer__c.field-meta.xml
<CustomField>
    <fullName>Buyer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Buyer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Reservations</relationshipLabel>
    <relationshipName>Reservations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Reservation__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>City</label>
    <referenceTo>City__c</referenceTo>
    <relationshipLabel>Reservations</relationshipLabel>
    <relationshipName>Reservations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Reservation__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Reservations</relationshipLabel>
    <relationshipName>Reservations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Reservation__c/fields/Listing__c.field-meta.xml
<CustomField>
    <fullName>Listing__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Listing</label>
    <referenceTo>Listings__c</referenceTo>
    <relationshipLabel>Reservations</relationshipLabel>
    <relationshipName>Reservations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Reservation__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Property</label>
    <referenceTo>Property__c</referenceTo>
    <relationshipLabel>Reservations</relationshipLabel>
    <relationshipName>Reservations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Reservation__c/fields/Reservation_Date__c.field-meta.xml
<CustomField>
    <fullName>Reservation_Date__c</fullName>
    <label>Reservation Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Reservation__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>State</label>
    <referenceTo>State__c</referenceTo>
    <relationshipLabel>Reservations</relationshipLabel>
    <relationshipName>Reservations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/State__c/State__c.object-meta.xml
<CustomObject>
    <label>State</label>
    <nameField>
        <label>State Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>States</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/State__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>States</relationshipLabel>
    <relationshipName>States</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AppointmentBookingScreenFlow_Apxcls.cls
global without sharing class AppointmentBookingScreenFlow_Apxcls {
   @InvocableMethod
   public static List<String> getDetails(List<data> dt) {
       
      publicevent__e eve = new publicevent__e();
      eve.Message__c = JSON.serialize(dt[0]);
      eve.Type__c = 'Appointment';
      List<Database.SaveResult> results = EventBus.publish(new List<publicevent__e> {eve});
      //AppointmentBookingScreenFlow_Apxcls.createDetails( JSON.serialize(dt[0]) );
      return new List<String>{'success'};
   }
   
   public static void createDetails( String jsn){
        data dt = (data)JSON.deserialize(jsn,data.class);
		System.debug('contactId'+dt.contactId);
        dt.recordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Buyer').getRecordTypeId();
        Contact cn = new Contact(  Salutation =dt.salutation, FirstName =dt.firstName, LastName =dt.lastName, Phone =dt.phn, Email =dt.email, recordTypeId = dt.recordTypeId  );
        if( !String.isEmpty(dt.contactId) && dt.contactId !='blank' ){
            cn.Id = dt.contactId;
        } 
        if( !String.isEmpty(dt.cityId) && dt.cityId !='blank'  ){
            cn.City__c = dt.cityId;
        } 
        if( !String.isEmpty(dt.stateId) && dt.stateId !='blank' ){
            cn.State__c = dt.stateId;
        } 
        if( !String.isEmpty(dt.countryId) && dt.countryId !='blank'){
            cn.Country__c = dt.countryId;
        } 
        cn.AccountId='0015j00001SFbHnAAL';
        upsert cn;

        Reservation__c res = new Reservation__c();
        res.Buyer__c = cn.Id;
        if( !String.isEmpty(dt.cityId) && dt.cityId !='blank'  ){
            res.City__c = dt.cityId;
        }
        if( !String.isEmpty(dt.stateId) && dt.stateId !='blank' ){
            res.State__c = dt.stateId;
        }
        
        if( !String.isEmpty(dt.countryId) && dt.countryId !='blank'){
            res.Country__c = dt.countryId;
        }
        
        res.Reservation_Date__c = dt.DatTime;
        res.Listing__c = dt.listingid;
        res.Property__c = dt.propertyId;
        insert res;
        
        Map<String,String> eml_Names = new Map<String,String>();
        
        List<OrgWideEmailAddress> owa = [select id, Address, DisplayName from OrgWideEmailAddress where DisplayName ='Valuehub' limit 1];
        
        
        Messaging.SingleEmailMessage msg = new Messaging.SingleEmailMessage();
        System.debug('sndEmail'+dt.sndEmail);
        System.debug('email'+dt.email);
        if(owa.Size()>0){
            msg.setOrgWideEmailAddressId(owa[0].id);
        }
        if( !String.isEmpty( dt.sndEmail ) ){
            msg.setToAddresses(new List<String>{dt.sndEmail});
            eml_Names.put(dt.sndEmail,dt.lastName +' '+dt.firstName);
        }else{
            msg.setToAddresses(new List<String>{dt.email});
            eml_Names.put(dt.email,dt.lastName +' '+dt.firstName);
        }
        msg.setSubject('Schedule Meeting with Valuehub Team');
        msg.setPlainTextBody('New Meeting is Scheduled');
        Messaging.EmailFileAttachment efa1 = new Messaging.EmailFileAttachment();
        efa1.setFileName('Salesforce-Meeting1.ics');
        Blob b1 = calenderinvite_ApxCls.doIcsAttachment( String.valueOf( cn.Id ), dt.DatTime, dt.DatTime.addHours(1), 'salesforce', 'New Meeting is Scheduled', 'Schedule Meeting with Valuehub Team', eml_Names, 1);
        efa1.setBody(b1);
        efa1.setContentType('text/calendar');
        msg.setFileAttachments(new Messaging.EmailFileAttachment[] {efa1});
        Messaging.sendEmail(new List<Messaging.SingleEmailMessage>{msg});
    }
    
   public class data{
        @InvocableVariable public String contactId;
        @InvocableVariable public String listingid;
        @InvocableVariable public String countryId;
		@InvocableVariable public String stateId;
        @InvocableVariable public String cityId;
        @InvocableVariable public String salutation;
		@InvocableVariable public String firstName;
        @InvocableVariable public String lastName;
        @InvocableVariable public String phn;
		@InvocableVariable public String email;
        @InvocableVariable public DateTime DatTime;
        @InvocableVariable public String sndEmail;
        @InvocableVariable public String propertyId;
        @InvocableVariable public String recordTypeId;
    }

}