force-app/main/default/objects/City__c/City__c.object-meta.xml
<CustomObject>
    <label>City</label>
    <nameField>
        <label>City Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/City__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>State</label>
    <referenceTo>State__c</referenceTo>
    <relationshipLabel>Cities</relationshipLabel>
    <relationshipName>Cities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <label>Country</label>
    <nameField>
        <label>Counrty Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Listings__c/Listings__c.object-meta.xml
<CustomObject>
    <description>A &quot;Listing&quot; is a data object representing a property available for sale or rent in the real estate industry. It typically includes property details (type, location, size), pricing information, contact details, and a unique identifier for tracking. Listings are fundamental for property search and real estate transactions.</description>
    <label>Listing</label>
    <nameField>
        <label>Listings Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Listings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Listings__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>City</label>
    <referenceTo>City__c</referenceTo>
    <relationshipLabel>Listings</relationshipLabel>
    <relationshipName>Listings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Listings__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Listings</relationshipLabel>
    <relationshipName>Listings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Listings__c/fields/Latitude__c.field-meta.xml
<CustomField>
    <fullName>Latitude__c</fullName>
    <label>Latitude</label>
    <scale>2</scale>
    <type>Location</type>
</CustomField>

force-app/main/default/objects/Listings__c/fields/Listing_Price__c.field-meta.xml
<CustomField>
    <fullName>Listing_Price__c</fullName>
    <label>Listing Price</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Listings__c/fields/Longitude__c.field-meta.xml
<CustomField>
    <fullName>Longitude__c</fullName>
    <label>Longitude</label>
    <scale>2</scale>
    <type>Location</type>
</CustomField>

force-app/main/default/objects/Listings__c/fields/No_of_Bathrooms__c.field-meta.xml
<CustomField>
    <fullName>No_of_Bathrooms__c</fullName>
    <label>No.of Bathrooms</label>
    <precision>12</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Listings__c/fields/No_of_Bedrooms__c.field-meta.xml
<CustomField>
    <fullName>No_of_Bedrooms__c</fullName>
    <label>No.of Bedrooms</label>
    <precision>12</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Listings__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <label>Property</label>
    <referenceTo>Property__c</referenceTo>
    <relationshipLabel>Listings</relationshipLabel>
    <relationshipName>Listings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Listings__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>State</label>
    <referenceTo>State__c</referenceTo>
    <relationshipLabel>Listings</relationshipLabel>
    <relationshipName>Listings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Listings__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Off-Market</fullName>
                <default>true</default>
                <label>Off-Market</label>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Under Contract</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Sold</fullName>
            </value>
            <value>
                <fullName>Rented</fullName>
            </value>
            <value>
                <fullName>Hold</fullName>
            </value>
            <value>
                <fullName>Reserved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Listings__c/fields/Street_Name__c.field-meta.xml
<CustomField>
    <fullName>Street_Name__c</fullName>
    <label>Street Name</label>
    <length>254</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <description>A &quot;Property&quot; object represents a physical real estate asset, such as a house, apartment, commercial space, or land. It serves as a fundamental data structure in real estate databases and platforms. A typical Property object includes essential attributes, such as property type, location, size, and associated features, providing comprehensive information for buyers, renters, and real estate professionals. This object plays a central role in real estate listings and transactions, facilitating property search, evaluation, and decision-making.</description>
    <label>Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Property__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>City</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>City__c.State__c</field>
            <operation>equals</operation>
            <valueField>$Source.State__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>City__c</referenceTo>
    <relationshipLabel>Properties</relationshipLabel>
    <relationshipName>Properties</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Properties</relationshipLabel>
    <relationshipName>Properties</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Property_Type__c.field-meta.xml
<CustomField>
    <fullName>Property_Type__c</fullName>
    <description>This picklist  for the different type properties</description>
    <inlineHelpText>Please Select the the Property Type</inlineHelpText>
    <label>Property Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Retail</fullName>
            </value>
            <value>
                <fullName>Multi Family</fullName>
            </value>
            <value>
                <fullName>Self Storage</fullName>
            </value>
            <value>
                <fullName>Single family residence</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Property__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>State</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>State__c.Country__c</field>
            <operation>equals</operation>
            <valueField>$Source.Country__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>State__c</referenceTo>
    <relationshipLabel>Properties</relationshipLabel>
    <relationshipName>Properties</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Sold</fullName>
            </value>
            <value>
                <fullName>Rented</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Property_Image__c/Property_Image__c.object-meta.xml
<CustomObject>
    <label>Property Image</label>
    <nameField>
        <label>Property Image Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Property Images</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Property_Image__c/fields/Image__c.field-meta.xml
<CustomField>
    <fullName>Image__c</fullName>
    <formula>IF(ISBLANK(Property_Image_URL__c), &apos;&apos;, IMAGE(Property_Image_URL__c, &quot;Image&quot;))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Image</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Property_Image__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Property</label>
    <referenceTo>Listings__c</referenceTo>
    <relationshipLabel>Property Images</relationshipLabel>
    <relationshipName>Property_Images</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Property_Image__c/fields/Property_Image_URL__c.field-meta.xml
<CustomField>
    <fullName>Property_Image_URL__c</fullName>
    <label>Property Image URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/State__c/State__c.object-meta.xml
<CustomObject>
    <label>State</label>
    <nameField>
        <label>State Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>States</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/State__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>States</relationshipLabel>
    <relationshipName>States</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/RealEstateController.cls
public class RealEstateController {
    @AuraEnabled(cacheable=true)
    public static List<Listings__c> getListingImages() {
        List<Listings__c> listings = [
            SELECT Id, Name, Latitude__c, Longitude__c, No_of_Bathrooms__c, No_of_Bedrooms__c, Listing_Price__c,
                City__r.Name, State__r.Name, Property__r.Name, Property__r.Status__c, Property__r.Property_Type__c,
                Country__r.Name, (SELECT Id, Property_Image_URL__c FROM Property_Images__r)
            FROM Listings__c LIMIT 20
        ];

        return listings;
    }
  /*
    @AuraEnabled(cacheable=true)
    public static List<Listings__c> getFilteredListingImages(Integer minPrice, Integer maxPrice, Integer minBedrooms, Integer minBathrooms, String selectedFilter, String searchCity, String searchCountry) {
        List<Listings__c> listings;

        // Build dynamic SOQL query based on provided filters
        String queryString = 'SELECT Id, Name, Latitude__c, Longitude__c, No_of_Bathrooms__c, No_of_Bedrooms__c, Listing_Price__c, ' +
            'City__r.Name, State__r.Name, Property__r.Name, Property__r.Status__c, ' +
            'Property__r.Property_Type__c, Country__r.Name, (SELECT Id, Property_Image_URL__c FROM Property_Images__r) ' +
            'FROM Listings__c WHERE ';

        List<String> conditions = new List<String>();

        if (minPrice != null && maxPrice != null) {
            conditions.add('Listing_Price__c >= ' + minPrice + ' AND Listing_Price__c <= ' + maxPrice);
        }

        if (minBedrooms != null) {
            conditions.add('No_of_Bedrooms__c = ' + minBedrooms);
        }

        if (minBathrooms != null) {
            conditions.add('No_of_Bathrooms__c = ' + minBathrooms);
        }

        if (selectedFilter != null && selectedFilter != 'All') {
            conditions.add('Property__r.Status__c = \'' + selectedFilter + '\'');
        }

        if (searchCity != null && !String.isBlank(searchCity.trim())) {
            conditions.add('City__r.Name LIKE \'' + searchCity + '\'');
        }

        if (searchCountry != null && !String.isBlank(searchCountry.trim())) {
            conditions.add('Country__r.Name LIKE \'' + searchCountry + '\'');
        }

        if (conditions.size() > 0) {
            queryString += String.join(conditions, ' AND ');
            queryString += ' LIMIT 50';

            listings = Database.query(queryString);
        } else {
            // If no filters are provided, fetch all listings
            listings = getListingImages();
        }

        return listings;
    }
   */
   
    @AuraEnabled(cacheable=true)
    public static List<Listings__c> getListingsWithImages(String selectedFilter, Decimal minPrice, Decimal maxPrice, String searchCity, String searchCountry ,Integer minBedrooms , Integer minBathrooms, List<String> selectedPropertyTypes) {
        // Add a debug statement to log the input parameters
        System.debug('selectedFilter: ' + selectedFilter);
        System.debug('minPrice: ' + minPrice);
        System.debug('maxPrice: ' + maxPrice);
        System.debug('searchCity: ' + searchCity);
		System.debug('selectedPropertyTypes: ' + selectedPropertyTypes.size());
        String soqlQuery = 'SELECT Id, Name, Latitude__c, Longitude__c, No_of_Bathrooms__c, No_of_Bedrooms__c,Listing_Price__c,Street_Name__c, ' +
            '(SELECT Id,Name, Property_Image_URL__c, Image__c FROM Property_Images__r), ' +
            'City__r.Name, State__r.Name, Property__r.Name, Property__r.Status__c, Property__r.Property_Type__c,Country__r.Name ' +
            'FROM Listings__c';
		soqlQuery += ' WHERE No_of_Bathrooms__c >= :minBathrooms AND No_of_Bedrooms__c >= :minBedrooms AND Listing_Price__c >=:minPrice';
           
        if (selectedFilter != 'All') {
            soqlQuery += ' AND Property__r.Status__c = :selectedFilter ';
        } 
        
        if( selectedPropertyTypes.size() > 0 ){
            soqlQuery += ' AND Property__r.Property_Type__c IN : selectedPropertyTypes';
        }
                                                             
        if (maxPrice > 0) {
            soqlQuery += ' AND Listing_Price__c <:maxPrice ';
        }        
        if (!String.isEmpty(searchCity) && searchCity != 'blank' ) {
           // soqlQuery += ' WHERE City__r.Name = :searchCity';
            soqlQuery += ' AND City__c =:searchCity';
        }
		if(!String.isEmpty(searchCountry) &&  searchCountry != 'blank' ){
            soqlQuery += ' AND Country__c  =:searchCountry';
        }
        
        
        // Add a debug statement to log the SOQL query
        System.debug('SOQL Query: ' + soqlQuery);

        soqlQuery += ' LIMIT 50';

        List<Listings__c> listingData = Database.query(soqlQuery);
		System.debug('SOQL Query: ' + listingData.Size());
        // Add a debug statement to log the results
       // System.debug('Listing Data: ' + listingData);

        return listingData;
    }
    
    @AuraEnabled(cacheable=true)
    public static List<String> getAllCityNames() {
        List<String> cityNames = new List<String>();

        for (AggregateResult ar : [
            SELECT City__r.Name cityName FROM Listings__c WHERE City__c != null GROUP BY City__r.Name
        ]) {
            String cityName = String.valueOf(ar.get('cityName'));
            cityNames.add(cityName);
        }

        return cityNames;
    }

    @AuraEnabled(cacheable=true)
    public static List<String> getAllCountryNames() {
        List<String> countryNames = new List<String>();

        for (AggregateResult ar : [
            SELECT Country__r.Name countryName FROM Listings__c WHERE Country__c != null GROUP BY Country__r.Name
        ]) {
            String countryName = String.valueOf(ar.get('countryName'));
            countryNames.add(countryName);
        }

        return countryNames;
    }
}